# Define the settings for each model
model_settings_magicpro_filter = {
    'GLOBAL': {
        'gaussian_blur': (5, 5),
        'clahe_clip_limit': 2.1,
        'clahe_tile_grid_size': (30, 30),
        'contrast_alpha': 1.1,
        'brightness_beta': 21,
        'adaptive_thresh_block_size': 85,
        'adaptive_thresh_C': 50,
        'dilate_kernel_size': (1, 1),
        'dilate_iterations': 1,
        'saturation_factor': 3.0,
        'h': 0,
        'hForColorComponents': 0,
        'templateWindowSize': 1,
        'searchWindowSize': 1,
        'adaptive_thresh_block_size_2': 95,
        'adaptive_thresh_C_2': 100,
        'dilate_kernel_size_2': (1, 1),
        'dilate_iterations_2': 1,
        'black_point': 10,
        'whiteness_adjustment': 1,
        'percentile_slider': 89.7,
        'color_palettes': {
            'custom': {
                'hue_shift': 0,
                'saturation_factor': 0.8,
                'brightness_beta': 10,
                'white_intensity': 1.0,
                'black_intensity': 0.4,
            }
        }
    },
    'SOPHACA': {
        'gaussian_blur': (5, 5),
        'clahe_clip_limit': 2.1,
        'clahe_tile_grid_size': (30, 30),
        'contrast_alpha': 1.1,
        'brightness_beta': 29,
        'adaptive_thresh_block_size': 85,
        'adaptive_thresh_C': 50,
        'dilate_kernel_size': (1, 1),
        'dilate_iterations': 1,
        'saturation_factor': 3.0,
        'h': 0,
        'hForColorComponents': 0,
        'templateWindowSize': 1,
        'searchWindowSize': 1,
        'adaptive_thresh_block_size_2': 95,
        'adaptive_thresh_C_2': 100,
        'dilate_kernel_size_2': (1, 1),
        'dilate_iterations_2': 1,
        'black_point': 10,
        'whiteness_adjustment': 1,
        'percentile_slider': 85.3,
        'color_palettes': {
            'custom': {
                'hue_shift': 0,
                'saturation_factor': 0.8,
                'brightness_beta': 10,
                'white_intensity': 1.0,
                'black_intensity': 0.4,
            }
        }
    },
    'SPR': {
        'gaussian_blur': (5, 5),
        'clahe_clip_limit': 1.0,
        'clahe_tile_grid_size': (30, 30),
        'contrast_alpha': 1.1,
        'brightness_beta': 21,
        'adaptive_thresh_block_size': 101,
        'adaptive_thresh_C': 50,
        'dilate_kernel_size': (1, 1),
        'dilate_iterations': 1,
        'saturation_factor': 4.0,
        'h': 15,
        'hForColorComponents': 0,
        'templateWindowSize': 1,
        'searchWindowSize': 1,
        'adaptive_thresh_block_size_2': 95,
        'adaptive_thresh_C_2': 100,
        'dilate_kernel_size_2': (1, 1),
        'dilate_iterations_2': 1,
        'black_point': 10,
        'whiteness_adjustment': 1,
        'percentile_slider': 82.4,
        'color_palettes': {
            'custom': {
                'hue_shift': 5,
                'saturation_factor': 0.7,
                'brightness_beta': 0,
                'white_intensity': 1.0,
                'black_intensity': 1.0,
            }
        }
    },
    'GPM': {
        'gaussian_blur': (3, 3),
        'clahe_clip_limit': 1.5,
        'clahe_tile_grid_size': (30, 30),
        'contrast_alpha': 1.0,
        'brightness_beta': 32,
        'adaptive_thresh_block_size': 101,
        'adaptive_thresh_C': 80,
        'dilate_kernel_size': (1, 1),
        'dilate_iterations': 1,
        'saturation_factor': 2.0,
        'h': 4,
        'hForColorComponents': 4,
        'templateWindowSize': 1,
        'searchWindowSize': 10,
        'adaptive_thresh_block_size_2': 101,
        'adaptive_thresh_C_2': 100,
        'dilate_kernel_size_2': (1, 1),
        'dilate_iterations_2': 1,
        'black_point': 10,
        'whiteness_adjustment': 1,
        'percentile_slider': 91.2,
        'color_palettes': {
            'custom': {
                'hue_shift': 0,
                'saturation_factor': 0.8,
                'brightness_beta': 9,
                'white_intensity': 1.0,
                'black_intensity': 0.4,
            }
        }
    },
    'SOPHADIMS': {
        'gaussian_blur': (5, 5),
        'clahe_clip_limit': 2.1,
        'clahe_tile_grid_size': (30, 30),
        'contrast_alpha': 1.1,
        'brightness_beta': 21,
        'adaptive_thresh_block_size': 85,
        'adaptive_thresh_C': 50,
        'dilate_kernel_size': (1, 1),
        'dilate_iterations': 1,
        'saturation_factor': 3.0,
        'h': 0,
        'hForColorComponents': 0,
        'templateWindowSize': 1,
        'searchWindowSize': 1,
        'adaptive_thresh_block_size_2': 95,
        'adaptive_thresh_C_2': 100,
        'dilate_kernel_size_2': (1, 1),
        'dilate_iterations_2': 1,
        'black_point': 10,
        'whiteness_adjustment': 1,
        'percentile_slider': 89.7,
        'color_palettes': {
            'custom': {
                'hue_shift': 0,
                'saturation_factor': 0.8,
                'brightness_beta': 10,
                'white_intensity': 1.0,
                'black_intensity': 0.4,
            }
        }
    },
    'RECAMED': {
        'gaussian_blur': (3, 3),
        'clahe_clip_limit': 7.0,
        'clahe_tile_grid_size': (40, 40),
        'contrast_alpha': 1.1,
        'brightness_beta': 10,
        'adaptive_thresh_block_size': 101,
        'adaptive_thresh_C': 70,
        'dilate_kernel_size': (1, 1),
        'dilate_iterations': 1,
        'saturation_factor': 3.0,
        'h': 10,
        'hForColorComponents': 0,
        'templateWindowSize': 1,
        'searchWindowSize': 10,
        'adaptive_thresh_block_size_2': 101,
        'adaptive_thresh_C_2': 100,
        'dilate_kernel_size_2': (1, 1),
        'dilate_iterations_2': 1,
        'black_point': 0,
        'whiteness_adjustment': 1,
        'percentile_slider': 80.0,
        'color_palettes': {
            'custom': {
                'hue_shift': 0,
                'saturation_factor': 0.8,
                'brightness_beta': 10,
                'white_intensity': 1.0,
                'black_intensity': 0.4,
            }
        }
    },
    'COOPER': {
        'gaussian_blur': (3, 3),
        'clahe_clip_limit': 1.5,
        'clahe_tile_grid_size': (20, 20),
        'contrast_alpha': 1.1,
        'brightness_beta': 40,
        'adaptive_thresh_block_size': 101,
        'adaptive_thresh_C': 40,
        'dilate_kernel_size': (1, 1),
        'dilate_iterations': 1,
        'saturation_factor': 1.5,
        'h': 2,
        'hForColorComponents': 0,
        'templateWindowSize': 1,
        'searchWindowSize': 1,
        'adaptive_thresh_block_size_2': 101,
        'adaptive_thresh_C_2': 100,
        'dilate_kernel_size_2': (1, 1),
        'dilate_iterations_2': 1,
        'black_point': 0,
        'whiteness_adjustment': 1,
        'percentile_slider': 35.0,
        'color_palettes': {
            'custom': {
                'hue_shift': 0,
                'saturation_factor': 0.8,
                'brightness_beta': 10,
                'white_intensity': 1.0,
                'black_intensity': 0.4,
            }
        }
    }
}
